/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellStoriesRouteImport } from './routes/_shell.stories'
import { Route as ShellHomeRouteImport } from './routes/_shell.home'
import { Route as ShellGetAroundRouteImport } from './routes/_shell.get-around'
import { Route as ShellExploreRouteImport } from './routes/_shell.explore'
import { Route as ShellAdventuresRouteImport } from './routes/_shell.adventures'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellStoriesRoute = ShellStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHomeRoute = ShellHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGetAroundRoute = ShellGetAroundRouteImport.update({
  id: '/get-around',
  path: '/get-around',
  getParentRoute: () => ShellRoute,
} as any)
const ShellExploreRoute = ShellExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdventuresRoute = ShellAdventuresRouteImport.update({
  id: '/adventures',
  path: '/adventures',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adventures': typeof ShellAdventuresRoute
  '/explore': typeof ShellExploreRoute
  '/get-around': typeof ShellGetAroundRoute
  '/home': typeof ShellHomeRoute
  '/stories': typeof ShellStoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adventures': typeof ShellAdventuresRoute
  '/explore': typeof ShellExploreRoute
  '/get-around': typeof ShellGetAroundRoute
  '/home': typeof ShellHomeRoute
  '/stories': typeof ShellStoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/adventures': typeof ShellAdventuresRoute
  '/_shell/explore': typeof ShellExploreRoute
  '/_shell/get-around': typeof ShellGetAroundRoute
  '/_shell/home': typeof ShellHomeRoute
  '/_shell/stories': typeof ShellStoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adventures'
    | '/explore'
    | '/get-around'
    | '/home'
    | '/stories'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adventures' | '/explore' | '/get-around' | '/home' | '/stories'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/adventures'
    | '/_shell/explore'
    | '/_shell/get-around'
    | '/_shell/home'
    | '/_shell/stories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/stories': {
      id: '/_shell/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof ShellStoriesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/home': {
      id: '/_shell/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ShellHomeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/get-around': {
      id: '/_shell/get-around'
      path: '/get-around'
      fullPath: '/get-around'
      preLoaderRoute: typeof ShellGetAroundRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/explore': {
      id: '/_shell/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ShellExploreRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/adventures': {
      id: '/_shell/adventures'
      path: '/adventures'
      fullPath: '/adventures'
      preLoaderRoute: typeof ShellAdventuresRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAdventuresRoute: typeof ShellAdventuresRoute
  ShellExploreRoute: typeof ShellExploreRoute
  ShellGetAroundRoute: typeof ShellGetAroundRoute
  ShellHomeRoute: typeof ShellHomeRoute
  ShellStoriesRoute: typeof ShellStoriesRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAdventuresRoute: ShellAdventuresRoute,
  ShellExploreRoute: ShellExploreRoute,
  ShellGetAroundRoute: ShellGetAroundRoute,
  ShellHomeRoute: ShellHomeRoute,
  ShellStoriesRoute: ShellStoriesRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
